name: Go

on:
  push:
    tags:
      - 'v*'

jobs:

  package:
    name: Packaging
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Create packages
        id: create-packages
        run: |
          git fetch --all --tags
          make package
          echo "##[set-output name=amd64;]$(ls -1 *-amd64.tar.gz)"
          echo "##[set-output name=arm;]$(ls -1 *-arm.tar.gz)"
          echo "##[set-output name=arm64;]$(ls -1 *-arm64.tar.gz)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        id: create-release
        with:
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          files: |
            ${{ steps.create-packages.outputs.amd64 }}
            ${{ steps.create-packages.outputs.arm }}
            ${{ steps.create-packages.outputs.arm64 }}
